/**
 * Copyright (c) 2025-2026 Capomastro Holdings Ltd. (Canada)
 * Patent(s) Pending — All Rights Reserved
 * Applied Physics Division
 *
 * Type declarations for TL-Sponge-385 WASM module.
 * Generated by wasm-pack build; this stub provides type information
 * when the WASM package is not yet compiled (e.g., CI type-check).
 *
 * Build WASM: cd ternary-math && wasm-pack build --target nodejs --out-dir pkg
 */

export function sponge_hash(input: Uint8Array, trit_count: number): Uint8Array;
export function sponge_keystream(domain: Uint8Array, trit_count: number): Uint8Array;
export function sponge_permutation(state: Uint8Array): Uint8Array;
export function sponge_permutation_v1(state: Uint8Array): Uint8Array;
