// Copyright (c) 2025-2026 Capomastro Holdings Ltd. (Canada)
// Patent(s) Pending — All Rights Reserved
// Applied Physics Division
//
// PROPRIETARY AND CONFIDENTIAL
// This file is part of the Salvi Framework / PlenumNET platform.
// See LICENSE in the repository root for full terms.

//! # Identity & Master Secret Management (T-12, SPEC-2026-NEXT)
//!
//! The master secret is the root of all cryptographic material for a node:
//!
//! - TL-DSA identity keypairs (T-15 address-bound keys)
//! - Heartbeat HMAC keys (T-08)
//! - Tunnel shared secrets (via TL-KEM)
//!
//! ## Security Requirements
//!
//! - **48 bytes (384 bits)** — matches TLSponge-385 security level
//! - **CSPRNG generated** — `getrandom` crate (OS entropy)
//! - **Encrypted at rest** — TLSponge-385 authenticated stream encryption
//! - **Zeroized on drop** — secret material never lingers in memory
//! - **Arc-epoch rotation** — every 182 days (π(π−1) = 14 × 13)
//! - **Dual-accept window** — 1 second (HPTP femtosecond sync)
//!
//! ## Encryption at Rest
//!
//! The master secret is encrypted using TLSponge-385 as both the KDF
//! and stream cipher — no external crypto dependency (no AES). The
//! encryption key is derived from a passphrase via TLSponge-385 KDF,
//! the keystream is generated by TLSponge-385, and the authentication
//! tag is a TLSponge-385 digest over (enc_key ‖ nonce ‖ ciphertext):
//!
//! ```text
//! enc_key    = TLSponge-385("PlenumNET-MS-ENC", passphrase ‖ salt, 32)
//! keystream  = TLSponge-385("PlenumNET-MS-STREAM", enc_key ‖ nonce, 48)
//! ciphertext = master_secret ⊕ keystream
//! tag        = TLSponge-385("PlenumNET-MS-TAG", enc_key ‖ nonce ‖ ciphertext, 16)
//! stored     = salt(16) ‖ nonce(12) ‖ ciphertext(48) ‖ tag(16)
//! ```
//!
//! When TPM 2.0 is available, the passphrase is replaced by a TPM-sealed
//! key — the encrypted blob is stored on disk, the sealing key never
//! leaves the TPM.
//!
//! ## Arc-Epoch Rotation
//!
//! Every 182 days (one arc = π(π−1)), the master secret rotates:
//!
//! 1. Generate new master secret
//! 2. Re-derive all dependent keys (HMAC, identity)
//! 3. Dual-accept window: both old and new secrets are valid
//! 4. After 182 days (max), old secret is zeroized
//!
//! Epoch boundaries: day 0, 182, 364 of the ternary year.

use std::time::{Duration, SystemTime, UNIX_EPOCH};

// ═══════════════════════════════════════════════════════════════════════
// CONSTANTS
// ═══════════════════════════════════════════════════════════════════════

/// Master secret length in bytes (384 bits = TLSponge-385 security level).
pub const MASTER_SECRET_LEN: usize = 48;

/// Salt length for passphrase-based encryption.
pub const SALT_LEN: usize = 16;

/// TLSponge-385 stream encryption nonce length.
pub const NONCE_LEN: usize = 12;

/// TLSponge-385 authentication tag length.
pub const TAG_LEN: usize = 16;

/// Encryption key length (256-bit, derived via TLSponge-385 KDF).
pub const ENC_KEY_LEN: usize = 32;

/// Total encrypted blob size: salt(16) + nonce(12) + ciphertext(48) + tag(16) = 92.
pub const ENCRYPTED_BLOB_LEN: usize = SALT_LEN + NONCE_LEN + MASTER_SECRET_LEN + TAG_LEN;

/// Domain separator for master secret encryption key derivation.
pub const MS_ENC_DOMAIN: &[u8] = b"PlenumNET-MS-ENC";

/// Domain separator for master secret generation from seed.
pub const MS_GEN_DOMAIN: &[u8] = b"PlenumNET-MS-GEN";

/// Arc epoch duration in seconds: 182 days = 15,724,800 seconds.
pub const ARC_EPOCH_SECS: u64 = 182 * 24 * 60 * 60;

/// Arc epoch duration.
pub const ARC_EPOCH_DURATION: Duration = Duration::from_secs(ARC_EPOCH_SECS);

/// Maximum dual-accept window: 1 second.
///
/// After rotation, the previous master secret remains valid for this
/// duration to cover in-flight messages signed under the old key.
/// On HPTP-synchronized infrastructure, 1 second is generous.
///
/// SYNC: Must equal `key_rotation::DUAL_ACCEPT_SECS`.
pub const MAX_DUAL_ACCEPT_SECS: u64 = 1;

/// Salvi Epoch: 2025-04-01T00:00:00Z (Unix timestamp).
/// All arc epochs are measured from this point.
pub const SALVI_EPOCH_UNIX: u64 = 1_743_465_600;

// ═══════════════════════════════════════════════════════════════════════
// ERRORS
// ═══════════════════════════════════════════════════════════════════════

/// Errors during identity/secret management.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IdentityError {
    /// Failed to generate random bytes.
    EntropyFailure,
    /// Passphrase is empty.
    EmptyPassphrase,
    /// Encrypted blob has wrong length.
    InvalidBlobLength { expected: usize, got: usize },
    /// Decryption failed (wrong passphrase or corrupted blob).
    DecryptionFailed,
    /// Master secret has wrong length.
    InvalidSecretLength { expected: usize, got: usize },
    /// Rotation attempted too early (current epoch hasn't ended).
    RotationTooEarly {
        current_epoch: u64,
        next_epoch_at: u64,
        now: u64,
    },
    /// Old secret has expired beyond dual-accept window.
    DualAcceptExpired,
}

impl std::fmt::Display for IdentityError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EntropyFailure => write!(f, "failed to generate random bytes"),
            Self::EmptyPassphrase => write!(f, "passphrase cannot be empty"),
            Self::InvalidBlobLength { expected, got } => {
                write!(f, "encrypted blob: expected {} bytes, got {}", expected, got)
            }
            Self::DecryptionFailed => write!(f, "decryption failed (wrong passphrase or corrupted)"),
            Self::InvalidSecretLength { expected, got } => {
                write!(f, "master secret: expected {} bytes, got {}", expected, got)
            }
            Self::RotationTooEarly { current_epoch, next_epoch_at, now } => {
                write!(
                    f,
                    "rotation too early: epoch {}, next at {}, now {}",
                    current_epoch, next_epoch_at, now
                )
            }
            Self::DualAcceptExpired => write!(f, "dual-accept window expired"),
        }
    }
}

impl std::error::Error for IdentityError {}

// ═══════════════════════════════════════════════════════════════════════
// MASTER SECRET — Zeroize-on-Drop wrapper
// ═══════════════════════════════════════════════════════════════════════

/// A master secret with automatic zeroization on drop.
///
/// The inner `Vec<u8>` is overwritten with zeros when this value is
/// dropped, preventing secret material from lingering in memory.
///
/// ## Usage
///
/// ```rust,ignore
/// let secret = MasterSecret::generate()?;
/// // Use secret.as_bytes() for key derivation
/// // secret is zeroized when it goes out of scope
/// ```
#[derive(Clone)]
pub struct MasterSecret {
    inner: Vec<u8>,
}

impl MasterSecret {
    /// Generate a new master secret from CSPRNG.
    ///
    /// Uses `getrandom` (OS entropy) for 48 bytes of randomness.
    /// Falls back to TLSponge-385 KDF with timestamp seed if
    /// `getrandom` is not available (shouldn't happen on Linux).
    pub fn generate() -> Result<Self, IdentityError> {
        let mut bytes = vec![0u8; MASTER_SECRET_LEN];

        getrandom::getrandom(&mut bytes)
            .map_err(|_| IdentityError::EntropyFailure)?;

        Ok(MasterSecret { inner: bytes })
    }

    /// Create from existing bytes (e.g., after decryption).
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, IdentityError> {
        if bytes.len() != MASTER_SECRET_LEN {
            return Err(IdentityError::InvalidSecretLength {
                expected: MASTER_SECRET_LEN,
                got: bytes.len(),
            });
        }
        Ok(MasterSecret {
            inner: bytes.to_vec(),
        })
    }

    /// Create a deterministic secret from a seed (for testing only).
    ///
    /// **NOT FOR PRODUCTION** — seeds must have full entropy.
    pub fn from_seed(seed: &[u8]) -> Self {
        let derived = ternary_math::sponge::derive_key(
            MS_GEN_DOMAIN,
            seed,
            MASTER_SECRET_LEN,
        );
        MasterSecret { inner: derived }
    }

    /// Get the raw secret bytes.
    pub fn as_bytes(&self) -> &[u8] {
        &self.inner
    }

    /// Secret length in bytes.
    pub fn len(&self) -> usize {
        self.inner.len()
    }

    /// Whether the secret is empty (should never be true for a valid secret).
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }

    /// Make `collect_entropy_seed` accessible to persistence module.
    pub(crate) fn entropy_seed() -> Vec<u8> {
        Self::collect_entropy_seed()
    }

    /// Collect entropy seed material.
    ///
    /// Combines multiple sources to build a high-entropy seed:
    /// - System time (nanosecond precision)
    /// - Process-specific data (thread ID hash)
    /// - A counter to ensure uniqueness across rapid calls
    fn collect_entropy_seed() -> Vec<u8> {
        let mut seed = Vec::with_capacity(64);

        // System time with nanosecond precision
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or(Duration::from_secs(0));
        seed.extend_from_slice(&now.as_nanos().to_le_bytes());

        // Thread-local counter for uniqueness
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let count = COUNTER.fetch_add(1, Ordering::Relaxed);
        seed.extend_from_slice(&count.to_le_bytes());

        // Extra entropy from stack address (ASLR)
        let stack_var: u64 = 0;
        let stack_addr = &stack_var as *const u64 as u64;
        seed.extend_from_slice(&stack_addr.to_le_bytes());

        seed
    }
}

impl Drop for MasterSecret {
    /// Zeroize the secret material on drop.
    ///
    /// Overwrites every byte with zero, then with 0xFF, then zero again
    /// to defeat potential compiler optimizations that might skip the
    /// first zeroing. Uses volatile writes to prevent elision.
    fn drop(&mut self) {
        // Three-pass zeroize to defeat optimization
        for b in self.inner.iter_mut() {
            unsafe {
                std::ptr::write_volatile(b as *mut u8, 0x00);
            }
        }
        for b in self.inner.iter_mut() {
            unsafe {
                std::ptr::write_volatile(b as *mut u8, 0xFF);
            }
        }
        for b in self.inner.iter_mut() {
            unsafe {
                std::ptr::write_volatile(b as *mut u8, 0x00);
            }
        }
    }
}

impl std::fmt::Debug for MasterSecret {
    /// Never print the actual secret — only metadata.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "MasterSecret({} bytes, REDACTED)", self.inner.len())
    }
}

// ═══════════════════════════════════════════════════════════════════════
// ENCRYPTION AT REST — Passphrase-based
// ═══════════════════════════════════════════════════════════════════════

/// Derive an encryption key from a passphrase and salt.
///
/// `enc_key = TLSponge-385("PlenumNET-MS-ENC", passphrase ‖ salt, 32)`
///
/// TLSponge-385 provides ≈385-bit pre-image resistance, making this
/// at least as strong as Argon2 with comparable parameters.
pub fn derive_enc_key(passphrase: &[u8], salt: &[u8]) -> [u8; ENC_KEY_LEN] {
    let mut material = Vec::with_capacity(passphrase.len() + salt.len());
    material.extend_from_slice(passphrase);
    material.extend_from_slice(salt);

    let key_bytes = ternary_math::sponge::derive_key(MS_ENC_DOMAIN, &material, ENC_KEY_LEN);
    let mut key = [0u8; ENC_KEY_LEN];
    key.copy_from_slice(&key_bytes);
    key
}

/// Encrypt a master secret with a passphrase.
///
/// Returns a self-contained blob: `salt(16) ‖ nonce(12) ‖ ciphertext(48) ‖ tag(16)`.
///
/// Uses TLSponge-385 exclusively — no external crypto dependencies.
/// The ciphertext is XOR-encrypted with a TLSponge-385 keystream derived
/// from the encryption key + nonce. An authentication tag (16 bytes) is
/// appended for integrity verification. Domain separation across all
/// derivation steps provides nonce-misuse resistance.
pub fn encrypt_master_secret(
    secret: &MasterSecret,
    passphrase: &[u8],
) -> Result<Vec<u8>, IdentityError> {
    if passphrase.is_empty() {
        return Err(IdentityError::EmptyPassphrase);
    }

    // Generate salt and nonce from entropy
    let salt_seed = MasterSecret::collect_entropy_seed();
    let salt_derived = ternary_math::sponge::derive_key(
        b"PlenumNET-MS-SALT",
        &salt_seed,
        SALT_LEN,
    );
    let mut salt = [0u8; SALT_LEN];
    salt.copy_from_slice(&salt_derived);

    let nonce_seed = MasterSecret::collect_entropy_seed();
    let nonce_derived = ternary_math::sponge::derive_key(
        b"PlenumNET-MS-NONCE",
        &nonce_seed,
        NONCE_LEN,
    );
    let mut nonce = [0u8; NONCE_LEN];
    nonce.copy_from_slice(&nonce_derived);

    // Derive encryption key
    let enc_key = derive_enc_key(passphrase, &salt);

    // Generate keystream from enc_key + nonce
    let mut ks_material = Vec::with_capacity(ENC_KEY_LEN + NONCE_LEN);
    ks_material.extend_from_slice(&enc_key);
    ks_material.extend_from_slice(&nonce);
    let keystream = ternary_math::sponge::derive_key(
        b"PlenumNET-MS-STREAM",
        &ks_material,
        MASTER_SECRET_LEN,
    );

    // XOR encrypt
    let mut ciphertext = vec![0u8; MASTER_SECRET_LEN];
    for i in 0..MASTER_SECRET_LEN {
        ciphertext[i] = secret.as_bytes()[i] ^ keystream[i];
    }

    // Authentication tag: TLSponge-385(enc_key ‖ nonce ‖ ciphertext)
    let mut tag_material = Vec::with_capacity(ENC_KEY_LEN + NONCE_LEN + MASTER_SECRET_LEN);
    tag_material.extend_from_slice(&enc_key);
    tag_material.extend_from_slice(&nonce);
    tag_material.extend_from_slice(&ciphertext);
    let tag = ternary_math::sponge::derive_key(
        b"PlenumNET-MS-TAG",
        &tag_material,
        TAG_LEN,
    );

    // Assemble blob: salt ‖ nonce ‖ ciphertext ‖ tag
    let mut blob = Vec::with_capacity(ENCRYPTED_BLOB_LEN);
    blob.extend_from_slice(&salt);
    blob.extend_from_slice(&nonce);
    blob.extend_from_slice(&ciphertext);
    blob.extend_from_slice(&tag);

    // Zeroize the encryption key
    let mut enc_key_z = enc_key;
    for b in enc_key_z.iter_mut() {
        unsafe { std::ptr::write_volatile(b as *mut u8, 0x00); }
    }

    Ok(blob)
}

/// Decrypt a master secret from an encrypted blob.
///
/// Parses `salt(16) ‖ nonce(12) ‖ ciphertext(48) ‖ tag(16)`, re-derives
/// the encryption key, verifies the tag, and decrypts.
pub fn decrypt_master_secret(
    blob: &[u8],
    passphrase: &[u8],
) -> Result<MasterSecret, IdentityError> {
    if blob.len() != ENCRYPTED_BLOB_LEN {
        return Err(IdentityError::InvalidBlobLength {
            expected: ENCRYPTED_BLOB_LEN,
            got: blob.len(),
        });
    }
    if passphrase.is_empty() {
        return Err(IdentityError::EmptyPassphrase);
    }

    // Parse blob
    let salt = &blob[..SALT_LEN];
    let nonce = &blob[SALT_LEN..SALT_LEN + NONCE_LEN];
    let ciphertext = &blob[SALT_LEN + NONCE_LEN..SALT_LEN + NONCE_LEN + MASTER_SECRET_LEN];
    let received_tag = &blob[SALT_LEN + NONCE_LEN + MASTER_SECRET_LEN..];

    // Re-derive encryption key
    let enc_key = derive_enc_key(passphrase, salt);

    // Verify tag BEFORE decrypting (authenticate-then-decrypt)
    let mut tag_material = Vec::with_capacity(ENC_KEY_LEN + NONCE_LEN + MASTER_SECRET_LEN);
    tag_material.extend_from_slice(&enc_key);
    tag_material.extend_from_slice(nonce);
    tag_material.extend_from_slice(ciphertext);
    let expected_tag = ternary_math::sponge::derive_key(
        b"PlenumNET-MS-TAG",
        &tag_material,
        TAG_LEN,
    );

    // Constant-time tag comparison
    let mut diff: u8 = 0;
    for i in 0..TAG_LEN {
        diff |= expected_tag[i] ^ received_tag[i];
    }
    if diff != 0 {
        return Err(IdentityError::DecryptionFailed);
    }

    // Generate keystream
    let mut ks_material = Vec::with_capacity(ENC_KEY_LEN + NONCE_LEN);
    ks_material.extend_from_slice(&enc_key);
    ks_material.extend_from_slice(nonce);
    let keystream = ternary_math::sponge::derive_key(
        b"PlenumNET-MS-STREAM",
        &ks_material,
        MASTER_SECRET_LEN,
    );

    // XOR decrypt
    let mut plaintext = vec![0u8; MASTER_SECRET_LEN];
    for i in 0..MASTER_SECRET_LEN {
        plaintext[i] = ciphertext[i] ^ keystream[i];
    }

    // Zeroize encryption key
    let mut enc_key_z = enc_key;
    for b in enc_key_z.iter_mut() {
        unsafe { std::ptr::write_volatile(b as *mut u8, 0x00); }
    }

    MasterSecret::from_bytes(&plaintext)
}

// ═══════════════════════════════════════════════════════════════════════
// ARC-EPOCH ROTATION
// ═══════════════════════════════════════════════════════════════════════

/// Compute the current arc epoch number.
///
/// Epochs are 182-day intervals measured from the Salvi Epoch.
/// Epoch 0: days 0–181, Epoch 1: days 182–363, Epoch 2: days 364–545, etc.
///
/// `epoch = (unix_timestamp - salvi_epoch) / arc_epoch_secs`
pub fn current_arc_epoch(unix_timestamp: u64) -> u64 {
    if unix_timestamp < SALVI_EPOCH_UNIX {
        return 0;
    }
    (unix_timestamp - SALVI_EPOCH_UNIX) / ARC_EPOCH_SECS
}

/// Compute the Unix timestamp when the next arc epoch begins.
pub fn next_epoch_start(unix_timestamp: u64) -> u64 {
    let epoch = current_arc_epoch(unix_timestamp);
    SALVI_EPOCH_UNIX + (epoch + 1) * ARC_EPOCH_SECS
}

/// Compute the Unix timestamp when the current arc epoch began.
pub fn epoch_start(unix_timestamp: u64) -> u64 {
    let epoch = current_arc_epoch(unix_timestamp);
    SALVI_EPOCH_UNIX + epoch * ARC_EPOCH_SECS
}

/// Days into the current arc epoch.
pub fn days_into_epoch(unix_timestamp: u64) -> u64 {
    let start = epoch_start(unix_timestamp);
    if unix_timestamp < start {
        return 0;
    }
    (unix_timestamp - start) / 86_400
}

/// Check if a rotation should be triggered at this timestamp.
///
/// Rotation is due when the current epoch is newer than the secret's epoch.
pub fn rotation_due(secret_epoch: u64, unix_timestamp: u64) -> bool {
    current_arc_epoch(unix_timestamp) > secret_epoch
}

/// Secret rotation state machine.
///
/// Manages the current and previous master secrets during the
/// dual-accept window after rotation.
#[derive(Debug)]
pub struct SecretRotation {
    /// Current (active) master secret.
    current: MasterSecret,
    /// Epoch when the current secret was generated.
    current_epoch: u64,
    /// Previous master secret (during dual-accept window).
    /// `None` if no rotation has occurred or the window has closed.
    previous: Option<MasterSecret>,
    /// Epoch when the previous secret was generated.
    previous_epoch: Option<u64>,
    /// Unix timestamp when the last rotation occurred.
    rotated_at: Option<u64>,
}

impl SecretRotation {
    /// Create a new rotation state with a fresh secret.
    pub fn new(secret: MasterSecret, epoch: u64) -> Self {
        SecretRotation {
            current: secret,
            current_epoch: epoch,
            previous: None,
            previous_epoch: None,
            rotated_at: None,
        }
    }

    /// Get the current master secret.
    pub fn current(&self) -> &MasterSecret {
        &self.current
    }

    /// Get the current epoch.
    pub fn current_epoch(&self) -> u64 {
        self.current_epoch
    }

    /// Get the previous master secret (if in dual-accept window).
    pub fn previous(&self) -> Option<&MasterSecret> {
        self.previous.as_ref()
    }

    /// Whether we're in the dual-accept window.
    pub fn in_dual_accept(&self) -> bool {
        self.previous.is_some()
    }

    /// Perform a rotation: new secret becomes current, old becomes previous.
    ///
    /// The previous secret is kept for the dual-accept window (max 182 days).
    pub fn rotate(
        &mut self,
        new_secret: MasterSecret,
        new_epoch: u64,
        unix_timestamp: u64,
    ) -> Result<(), IdentityError> {
        // Ensure we're actually in a new epoch
        if new_epoch <= self.current_epoch {
            return Err(IdentityError::RotationTooEarly {
                current_epoch: self.current_epoch,
                next_epoch_at: SALVI_EPOCH_UNIX + (self.current_epoch + 1) * ARC_EPOCH_SECS,
                now: unix_timestamp,
            });
        }

        // Move current → previous
        let old_current = std::mem::replace(&mut self.current, new_secret);
        let old_epoch = self.current_epoch;
        self.current_epoch = new_epoch;

        // Zeroize any existing previous secret before replacing
        self.previous = Some(old_current);
        self.previous_epoch = Some(old_epoch);
        self.rotated_at = Some(unix_timestamp);

        Ok(())
    }

    /// Check and close the dual-accept window if expired.
    ///
    /// Call periodically (e.g., on each heartbeat cycle). If the window
    /// has exceeded 182 days, zeroize the previous secret.
    pub fn check_dual_accept(&mut self, unix_timestamp: u64) {
        if let Some(rotated_at) = self.rotated_at {
            if unix_timestamp > rotated_at + MAX_DUAL_ACCEPT_SECS {
                // Window expired — zeroize previous
                self.previous = None;
                self.previous_epoch = None;
                self.rotated_at = None;
            }
        }
    }

    /// Try to verify/derive against both secrets (current first, then previous).
    ///
    /// Returns `(result, which_secret)` where `which_secret` is `true` for
    /// current, `false` for previous. Useful for HMAC key derivation during
    /// the dual-accept window.
    pub fn derive_with_fallback<F, R>(&self, f: F) -> Option<(R, bool)>
    where
        F: Fn(&MasterSecret) -> Option<R>,
    {
        // Try current first
        if let Some(result) = f(&self.current) {
            return Some((result, true));
        }
        // Try previous if in dual-accept
        if let Some(ref prev) = self.previous {
            if let Some(result) = f(prev) {
                return Some((result, false));
            }
        }
        None
    }
}

// ═══════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    // ── Master secret generation ────────────────────────────────

    #[test]
    fn test_generate_correct_length() {
        let secret = MasterSecret::generate().unwrap();
        assert_eq!(secret.len(), MASTER_SECRET_LEN);
    }

    #[test]
    fn test_generate_unique() {
        let s1 = MasterSecret::generate().unwrap();
        let s2 = MasterSecret::generate().unwrap();
        assert_ne!(
            s1.as_bytes(), s2.as_bytes(),
            "Two generated secrets must differ"
        );
    }

    #[test]
    fn test_from_seed_deterministic() {
        let s1 = MasterSecret::from_seed(b"test-seed");
        let s2 = MasterSecret::from_seed(b"test-seed");
        assert_eq!(s1.as_bytes(), s2.as_bytes());
    }

    #[test]
    fn test_from_seed_different_seeds() {
        let s1 = MasterSecret::from_seed(b"seed-alpha");
        let s2 = MasterSecret::from_seed(b"seed-beta");
        assert_ne!(s1.as_bytes(), s2.as_bytes());
    }

    #[test]
    fn test_from_bytes_correct_length() {
        let bytes = [42u8; MASTER_SECRET_LEN];
        let secret = MasterSecret::from_bytes(&bytes).unwrap();
        assert_eq!(secret.as_bytes(), &bytes);
    }

    #[test]
    fn test_from_bytes_wrong_length() {
        let bytes = [42u8; 32]; // Too short
        assert!(matches!(
            MasterSecret::from_bytes(&bytes),
            Err(IdentityError::InvalidSecretLength { expected: 48, got: 32 })
        ));
    }

    #[test]
    fn test_debug_redacted() {
        let secret = MasterSecret::from_seed(b"test");
        let debug = format!("{:?}", secret);
        assert!(debug.contains("REDACTED"));
        assert!(!debug.contains("42")); // No actual bytes
    }

    #[test]
    fn test_zeroize_on_drop() {
        let ptr: *const u8;
        {
            let secret = MasterSecret::from_seed(b"zeroize-test");
            ptr = secret.as_bytes().as_ptr();
            // secret is dropped here
        }
        // After drop, the memory SHOULD be zeroed.
        // We can't reliably test this because the allocator may have
        // reused the memory, but the Drop impl runs the volatile writes.
        // This test just ensures Drop doesn't panic.
        let _ = ptr; // Prevent unused warning
    }

    // ── Encryption at rest ──────────────────────────────────────

    #[test]
    fn test_encrypt_decrypt_roundtrip() {
        let secret = MasterSecret::from_seed(b"encrypt-test");
        let passphrase = b"my-strong-passphrase";

        let blob = encrypt_master_secret(&secret, passphrase).unwrap();
        assert_eq!(blob.len(), ENCRYPTED_BLOB_LEN);

        let decrypted = decrypt_master_secret(&blob, passphrase).unwrap();
        assert_eq!(decrypted.as_bytes(), secret.as_bytes());
    }

    #[test]
    fn test_encrypt_wrong_passphrase_fails() {
        let secret = MasterSecret::from_seed(b"wrong-pass-test");
        let blob = encrypt_master_secret(&secret, b"correct-pass").unwrap();

        let result = decrypt_master_secret(&blob, b"wrong-pass");
        assert_eq!(result.unwrap_err(), IdentityError::DecryptionFailed);
    }

    #[test]
    fn test_encrypt_empty_passphrase_fails() {
        let secret = MasterSecret::from_seed(b"test");
        assert_eq!(
            encrypt_master_secret(&secret, b"").unwrap_err(),
            IdentityError::EmptyPassphrase
        );
    }

    #[test]
    fn test_decrypt_empty_passphrase_fails() {
        let blob = vec![0u8; ENCRYPTED_BLOB_LEN];
        assert_eq!(
            decrypt_master_secret(&blob, b"").unwrap_err(),
            IdentityError::EmptyPassphrase
        );
    }

    #[test]
    fn test_decrypt_wrong_blob_length() {
        assert!(matches!(
            decrypt_master_secret(&[0u8; 50], b"pass"),
            Err(IdentityError::InvalidBlobLength { expected: 92, got: 50 })
        ));
    }

    #[test]
    fn test_decrypt_corrupted_blob() {
        let secret = MasterSecret::from_seed(b"corrupt-test");
        let mut blob = encrypt_master_secret(&secret, b"pass").unwrap();
        // Corrupt one byte in the ciphertext
        blob[SALT_LEN + NONCE_LEN + 10] ^= 0xFF;
        assert_eq!(
            decrypt_master_secret(&blob, b"pass").unwrap_err(),
            IdentityError::DecryptionFailed
        );
    }

    #[test]
    fn test_different_encryptions_produce_different_blobs() {
        let secret = MasterSecret::from_seed(b"diff-test");
        let blob1 = encrypt_master_secret(&secret, b"pass").unwrap();
        let blob2 = encrypt_master_secret(&secret, b"pass").unwrap();
        // Different salt + nonce → different blobs
        assert_ne!(blob1, blob2, "Different encryptions must produce different blobs");
        // But both decrypt to the same secret
        let d1 = decrypt_master_secret(&blob1, b"pass").unwrap();
        let d2 = decrypt_master_secret(&blob2, b"pass").unwrap();
        assert_eq!(d1.as_bytes(), d2.as_bytes());
    }

    // ── Encryption key derivation ───────────────────────────────

    #[test]
    fn test_enc_key_deterministic() {
        let k1 = derive_enc_key(b"pass", b"salt");
        let k2 = derive_enc_key(b"pass", b"salt");
        assert_eq!(k1, k2);
    }

    #[test]
    fn test_enc_key_different_pass() {
        let k1 = derive_enc_key(b"pass1", b"salt");
        let k2 = derive_enc_key(b"pass2", b"salt");
        assert_ne!(k1, k2);
    }

    #[test]
    fn test_enc_key_different_salt() {
        let k1 = derive_enc_key(b"pass", b"salt1");
        let k2 = derive_enc_key(b"pass", b"salt2");
        assert_ne!(k1, k2);
    }

    // ── Arc epoch computation ───────────────────────────────────

    #[test]
    fn test_epoch_at_salvi_epoch() {
        assert_eq!(current_arc_epoch(SALVI_EPOCH_UNIX), 0);
    }

    #[test]
    fn test_epoch_day_181() {
        let day181 = SALVI_EPOCH_UNIX + 181 * 86400;
        assert_eq!(current_arc_epoch(day181), 0);
    }

    #[test]
    fn test_epoch_day_182() {
        let day182 = SALVI_EPOCH_UNIX + 182 * 86400;
        assert_eq!(current_arc_epoch(day182), 1);
    }

    #[test]
    fn test_epoch_day_364() {
        let day364 = SALVI_EPOCH_UNIX + 364 * 86400;
        assert_eq!(current_arc_epoch(day364), 2);
    }

    #[test]
    fn test_next_epoch_start() {
        let now = SALVI_EPOCH_UNIX + 100 * 86400; // Day 100
        let next = next_epoch_start(now);
        assert_eq!(next, SALVI_EPOCH_UNIX + 182 * 86400);
    }

    #[test]
    fn test_days_into_epoch() {
        let day50 = SALVI_EPOCH_UNIX + 50 * 86400;
        assert_eq!(days_into_epoch(day50), 50);
    }

    #[test]
    fn test_rotation_due() {
        let now_epoch1 = SALVI_EPOCH_UNIX + 200 * 86400;
        assert!(rotation_due(0, now_epoch1));
        assert!(!rotation_due(1, now_epoch1));
    }

    // ── Secret rotation ─────────────────────────────────────────

    #[test]
    fn test_rotation_basic() {
        let s1 = MasterSecret::from_seed(b"epoch-0");
        let mut rotation = SecretRotation::new(s1, 0);
        assert_eq!(rotation.current_epoch(), 0);
        assert!(!rotation.in_dual_accept());

        let s2 = MasterSecret::from_seed(b"epoch-1");
        let ts = SALVI_EPOCH_UNIX + 200 * 86400;
        rotation.rotate(s2, 1, ts).unwrap();

        assert_eq!(rotation.current_epoch(), 1);
        assert!(rotation.in_dual_accept());
        assert!(rotation.previous().is_some());
    }

    #[test]
    fn test_rotation_too_early() {
        let s1 = MasterSecret::from_seed(b"epoch-0");
        let mut rotation = SecretRotation::new(s1, 0);

        let s2 = MasterSecret::from_seed(b"same-epoch");
        let err = rotation.rotate(s2, 0, SALVI_EPOCH_UNIX).unwrap_err();
        assert!(matches!(err, IdentityError::RotationTooEarly { .. }));
    }

    #[test]
    fn test_dual_accept_expires() {
        let s1 = MasterSecret::from_seed(b"epoch-0");
        let mut rotation = SecretRotation::new(s1, 0);

        let s2 = MasterSecret::from_seed(b"epoch-1");
        let ts = SALVI_EPOCH_UNIX + 200 * 86400;
        rotation.rotate(s2, 1, ts).unwrap();
        assert!(rotation.in_dual_accept());

        // Check at ts + 183 days (beyond 182-day window)
        let expired = ts + 183 * 86400;
        rotation.check_dual_accept(expired);
        assert!(!rotation.in_dual_accept(), "Window should be closed");
        assert!(rotation.previous().is_none());
    }

    #[test]
    fn test_derive_with_fallback_current() {
        let s1 = MasterSecret::from_seed(b"current");
        let rotation = SecretRotation::new(s1, 0);

        let result = rotation.derive_with_fallback(|s| {
            if s.as_bytes()[0] != 0 { Some(42) } else { None }
        });
        assert_eq!(result, Some((42, true))); // true = current
    }

    #[test]
    fn test_derive_with_fallback_previous() {
        let s1 = MasterSecret::from_seed(b"old");
        let mut rotation = SecretRotation::new(s1, 0);
        let s2 = MasterSecret::from_seed(b"new");
        rotation.rotate(s2, 1, SALVI_EPOCH_UNIX + 200 * 86400).unwrap();

        // Closure that only matches the old secret's first byte
        let old_byte = MasterSecret::from_seed(b"old").as_bytes()[0];
        let result = rotation.derive_with_fallback(|s| {
            if s.as_bytes()[0] == old_byte { Some(99) } else { None }
        });
        assert_eq!(result, Some((99, false))); // false = previous
    }

    // ── Constants ───────────────────────────────────────────────

    #[test]
    fn test_constants() {
        assert_eq!(MASTER_SECRET_LEN, 48);
        assert_eq!(ENCRYPTED_BLOB_LEN, 92); // 16 + 12 + 48 + 16
        assert_eq!(ARC_EPOCH_SECS, 182 * 86400);
        assert_eq!(MAX_DUAL_ACCEPT_SECS, 1, "Dual-accept window must be 1 second (SYNC: key_rotation::DUAL_ACCEPT_SECS)");
    }
}