#!/usr/bin/env python3
"""
XPlenum riscv-formal Instruction Property Generator (Task 8A.1)

Generates SVA property modules for all 21 XPlenum instructions,
compatible with the riscv-formal RVFI trace interface.

Each generated module asserts:
  - Correct opcode/funct3/funct7 decoding
  - Pre-conditions on source operands (where applicable)
  - Post-conditions on destination register
  - Side-effects on CSRs (where applicable)
  - No unintended register file modifications
  - Exception conditions (privilege violations, domain faults)

Usage: python3 xplenum_rvfi_insn_gen.py --output-dir formal/generated/
"""

import os
import argparse
from dataclasses import dataclass
from typing import List, Optional

@dataclass
class XPlenumInsn:
    name: str
    mnemonic: str
    opcode: int
    funct3: int
    funct7: int
    unit: str
    has_rd: bool
    has_rs1: bool
    has_rs2: bool
    csr_side_effect: Optional[str]
    can_trap: bool
    description: str

XPLENUM_INSNS: List[XPlenumInsn] = [
    XPlenumInsn("XMASK_APPLY",   "xmask.apply",   0x0B, 0x0, 0x00, "mask",   True,  True,  True,  None,          False, "Apply boolean mask: rd = mask_op(rs1, rs2)"),
    XPlenumInsn("XMASK_STRIP",   "xmask.strip",   0x0B, 0x0, 0x01, "mask",   True,  True,  True,  None,          False, "Remove mask: rd = unmask_op(rs1, rs2)"),
    XPlenumInsn("XMASK_REFRESH", "xmask.refresh",  0x0B, 0x0, 0x02, "mask",   True,  True,  False, None,          False, "Re-randomise mask shares: rd = refresh(rs1)"),
    XPlenumInsn("XMASK_RNG",     "xmask.rng",     0x0B, 0x0, 0x03, "mask",   True,  False, False, "XMASK_STATUS", False, "Generate DRBG random: rd = drbg_generate()"),

    XPlenumInsn("XDOM_SET",      "xdom.set",      0x0B, 0x1, 0x00, "domain", False, True,  True,  "XDOM_ACTIVE",  False, "Set domain entry: table[rs1] = rs2"),
    XPlenumInsn("XDOM_GET",      "xdom.get",      0x0B, 0x1, 0x01, "domain", True,  True,  False, None,           False, "Get domain entry: rd = table[rs1]"),
    XPlenumInsn("XDOM_CHK",      "xdom.chk",      0x0B, 0x1, 0x02, "domain", True,  True,  True,  None,           True,  "Check domain permission: rd = check(rs1, rs2), trap on violation"),
    XPlenumInsn("XDOM_CLR",      "xdom.clr",      0x0B, 0x1, 0x03, "domain", False, True,  False, "XDOM_ACTIVE",  False, "Clear domain entry: table[rs1] = 0"),

    XPlenumInsn("XCAP_MINT",     "xcap.mint",     0x0B, 0x2, 0x00, "cap",    True,  True,  True,  "XCAP_COUNT",   False, "Mint capability: rd = new_cap(rs1_perms, rs2_bounds)"),
    XPlenumInsn("XCAP_CHK",      "xcap.chk",      0x0B, 0x2, 0x01, "cap",    True,  True,  True,  None,           True,  "Check capability: rd = valid(rs1_cap, rs2_access), trap if invalid"),
    XPlenumInsn("XCAP_REV",      "xcap.rev",      0x0B, 0x2, 0x02, "cap",    False, True,  False, "XCAP_COUNT",   False, "Revoke capability: invalidate(rs1_cap_id)"),
    XPlenumInsn("XCAP_SHR",      "xcap.shr",      0x0B, 0x2, 0x03, "cap",    True,  True,  True,  "XCAP_COUNT",   False, "Share capability: rd = delegate(rs1_cap, rs2_target)"),

    XPlenumInsn("XTRIT_ADD",     "xtrit.add",     0x2B, 0x0, 0x00, "trit",   True,  True,  True,  None,           False, "Ternary addition: rd = trit_add(rs1, rs2)"),
    XPlenumInsn("XTRIT_MUL",     "xtrit.mul",     0x2B, 0x0, 0x01, "trit",   True,  True,  True,  None,           False, "Ternary multiplication: rd = trit_mul(rs1, rs2)"),
    XPlenumInsn("XTRIT_TBOX",    "xtrit.tbox",    0x2B, 0x1, 0x00, "trit",   True,  True,  True,  None,           False, "T-box substitution: rd = tbox_lookup(rs1, rs2)"),
    XPlenumInsn("XTRIT_ROT",     "xtrit.rot",     0x2B, 0x1, 0x01, "trit",   True,  True,  True,  None,           False, "Bit rotation: rd = rotate(rs1, rs2)"),
    XPlenumInsn("XTRIT_ENC",     "xtrit.enc",     0x2B, 0x2, 0x00, "trit",   True,  True,  False, None,           False, "Balanced ternary encode: rd = to_balanced(rs1)"),
    XPlenumInsn("XTRIT_DEC",     "xtrit.dec",     0x2B, 0x2, 0x01, "trit",   True,  True,  False, None,           False, "Balanced ternary decode: rd = from_balanced(rs1)"),
    XPlenumInsn("XTRIT_MAC",     "xtrit.mac",     0x2B, 0x3, 0x00, "trit",   True,  True,  True,  None,           False, "Multiply-accumulate: rd = rs1 * rs2 + acc"),
    XPlenumInsn("XTRIT_FIR",     "xtrit.fir",     0x2B, 0x3, 0x01, "trit",   True,  True,  True,  None,           False, "FIR filter tap: rd = fir_step(rs1_sample, rs2_coeff)"),
    XPlenumInsn("XTRIT_FFT",     "xtrit.fft",     0x2B, 0x3, 0x02, "trit",   True,  True,  True,  None,           False, "FFT butterfly: rd = butterfly(rs1, rs2)"),
]

PROPERTY_TEMPLATE = """\
// ===================================================================
// riscv-formal Property Module: {name}
// Instruction: {mnemonic}
// Unit: {unit} | Opcode: 0x{opcode:02X} | funct3: {funct3} | funct7: 0x{funct7:02X}
// Generated by xplenum_rvfi_insn_gen.py -- Task 8A.1
// ===================================================================
`timescale 1ns/1ps

module rvfi_insn_{name_lower} (
    input         clk,
    input         rst_n,

    // RVFI Trace Interface (from core wrapper)
    input         rvfi_valid,
    input  [63:0] rvfi_order,
    input  [31:0] rvfi_insn,
    input         rvfi_trap,
    input         rvfi_halt,
    input  [4:0]  rvfi_rs1_addr,
    input  [4:0]  rvfi_rs2_addr,
    input  [63:0] rvfi_rs1_rdata,
    input  [63:0] rvfi_rs2_rdata,
    input  [4:0]  rvfi_rd_addr,
    input  [63:0] rvfi_rd_wdata,
    input  [63:0] rvfi_pc_rdata,
    input  [63:0] rvfi_pc_wdata,
    input  [1:0]  rvfi_mode       // 0=U, 1=S, 3=M
);

    // -- Instruction field extraction --
    wire [6:0]  insn_opcode = rvfi_insn[6:0];
    wire [2:0]  insn_funct3 = rvfi_insn[14:12];
    wire [6:0]  insn_funct7 = rvfi_insn[31:25];
    wire [4:0]  insn_rd     = rvfi_insn[11:7];
    wire [4:0]  insn_rs1    = rvfi_insn[19:15];
    wire [4:0]  insn_rs2    = rvfi_insn[24:20];

    // -- Instruction match --
    wire insn_match = (insn_opcode == 7'h{opcode:02X})
                    && (insn_funct3 == 3'd{funct3})
                    && (insn_funct7 == 7'h{funct7:02X});

    wire insn_active = rvfi_valid && insn_match && !rvfi_halt;

    // ===================================================================
    // Property 1: Correct Decode -- instruction fields match
    // ===================================================================
    property p_decode_match;
        @(posedge clk) disable iff (!rst_n)
        insn_active |->
            (rvfi_rs1_addr == insn_rs1) &&
            (rvfi_rs2_addr == insn_rs2);
    endproperty
    assert property (p_decode_match)
        else $error("[{name}] Decode mismatch: rs1/rs2 addr incorrect");

    // ===================================================================
    // Property 2: Register destination correctness
    // ===================================================================
{rd_property}

    // ===================================================================
    // Property 3: Exception / Trap conditions
    // ===================================================================
{trap_property}

    // ===================================================================
    // Property 4: Privilege enforcement (M-mode only for CSR ops)
    // ===================================================================
{privilege_property}

    // ===================================================================
    // Property 5: No side-effects on non-target registers
    // ===================================================================
    property p_no_spurious_write;
        @(posedge clk) disable iff (!rst_n)
        insn_active && {has_rd_cond} |->
            (rvfi_rd_addr == insn_rd);
    endproperty
    assert property (p_no_spurious_write)
        else $error("[{name}] Spurious write to unexpected register");

    // ===================================================================
    // Property 6: PC advances correctly (no unexpected branch)
    // ===================================================================
    property p_pc_advance;
        @(posedge clk) disable iff (!rst_n)
        insn_active && !rvfi_trap |->
            (rvfi_pc_wdata == rvfi_pc_rdata + 4);
    endproperty
    assert property (p_pc_advance)
        else $error("[{name}] PC did not advance by 4 on non-trap execution");

{unit_specific_properties}

endmodule
"""


def gen_rd_property(insn: XPlenumInsn) -> str:
    if insn.has_rd:
        return f"""    property p_rd_written;
        @(posedge clk) disable iff (!rst_n)
        insn_active && !rvfi_trap |->
            (rvfi_rd_addr == insn_rd) &&
            (rvfi_rd_addr != 5'd0);  // x0 never written
    endproperty
    assert property (p_rd_written)
        else $error("[{insn.name}] rd not written or wrote to x0");"""
    else:
        return f"""    property p_no_rd_write;
        @(posedge clk) disable iff (!rst_n)
        insn_active |->
            (rvfi_rd_wdata == 64'd0) && (rvfi_rd_addr == 5'd0);
    endproperty
    assert property (p_no_rd_write)
        else $error("[{insn.name}] Unexpected rd write on void instruction");"""


def gen_trap_property(insn: XPlenumInsn) -> str:
    if insn.can_trap:
        return f"""    // {insn.name} can legitimately trap (domain/cap violation)
    // Verify trap implies PC redirects to MTVEC
    property p_trap_redirect;
        @(posedge clk) disable iff (!rst_n)
        insn_active && rvfi_trap |->
            (rvfi_pc_wdata != rvfi_pc_rdata + 4);  // PC must redirect
    endproperty
    assert property (p_trap_redirect)
        else $error("[{insn.name}] Trap did not redirect PC");"""
    else:
        return f"""    // {insn.name} should never trap on valid inputs
    property p_no_unexpected_trap;
        @(posedge clk) disable iff (!rst_n)
        insn_active && (rvfi_mode == 2'd3) |->  // M-mode, valid inputs
            !rvfi_trap;
    endproperty
    assert property (p_no_unexpected_trap)
        else $error("[{insn.name}] Unexpected trap in M-mode");"""


def gen_privilege_property(insn: XPlenumInsn) -> str:
    if insn.csr_side_effect:
        return f"""    // CSR side-effect ({insn.csr_side_effect}) requires M-mode
    property p_privilege_enforcement;
        @(posedge clk) disable iff (!rst_n)
        insn_active && (rvfi_mode != 2'd3) |->
            rvfi_trap;  // Must trap if not M-mode
    endproperty
    assert property (p_privilege_enforcement)
        else $error("[{insn.name}] CSR access from non-M-mode did not trap");"""
    else:
        return f"""    // No CSR side-effect -- privilege check deferred to unit
    // (Domain/Cap units enforce internally)"""


def gen_unit_specific(insn: XPlenumInsn) -> str:
    props = []

    if insn.unit == "mask":
        if insn.name == "XMASK_APPLY":
            props.append("""
    // ===================================================================
    // Masking Property: Output differs from both inputs
    // (Statistical -- a masked value should not equal plaintext)
    // ===================================================================
    property p_mask_nontrivial;
        @(posedge clk) disable iff (!rst_n)
        insn_active && !rvfi_trap &&
        (rvfi_rs1_rdata != 64'd0) && (rvfi_rs2_rdata != 64'd0) |->
            (rvfi_rd_wdata != rvfi_rs1_rdata);  // Masked != plaintext
    endproperty
    assert property (p_mask_nontrivial)
        else $error("[XMASK_APPLY] Masked output equals plaintext -- masking ineffective");""")

        elif insn.name == "XMASK_RNG":
            props.append("""
    // ===================================================================
    // DRBG Property: Consecutive outputs must differ
    // ===================================================================
    reg [63:0] prev_rng_output;
    reg        prev_rng_valid;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            prev_rng_output <= 64'd0;
            prev_rng_valid  <= 1'b0;
        end else if (insn_active && !rvfi_trap) begin
            prev_rng_output <= rvfi_rd_wdata;
            prev_rng_valid  <= 1'b1;
        end
    end

    property p_rng_no_repeat;
        @(posedge clk) disable iff (!rst_n)
        insn_active && !rvfi_trap && prev_rng_valid |->
            (rvfi_rd_wdata != prev_rng_output);
    endproperty
    assert property (p_rng_no_repeat)
        else $error("[XMASK_RNG] DRBG produced identical consecutive outputs -- health test failure");""")

    elif insn.unit == "domain":
        if insn.name == "XDOM_CHK":
            props.append("""
    // ===================================================================
    // Domain Check: Violation must trap, valid access must not
    // ===================================================================
    // Note: Requires shadow model of domain table for full proof
    // This property verifies trap/no-trap consistency
    property p_domain_trap_consistency;
        @(posedge clk) disable iff (!rst_n)
        insn_active |->
            (rvfi_trap && (rvfi_rd_wdata == 64'd0)) ||
            (!rvfi_trap && (rvfi_rd_wdata != 64'd0));
    endproperty
    assert property (p_domain_trap_consistency)
        else $error("[XDOM_CHK] Trap/result inconsistency");""")

    elif insn.unit == "cap":
        if insn.name == "XCAP_REV":
            props.append("""
    // ===================================================================
    // Capability Revocation: O(1) -- must complete in bounded cycles
    // ===================================================================
    // This is a liveness property: revocation cannot stall indefinitely
    property p_revoke_bounded;
        @(posedge clk) disable iff (!rst_n)
        insn_active |->
            ##[0:3] (!rvfi_trap || rvfi_valid);  // Complete within 3 cycles
    endproperty
    assert property (p_revoke_bounded)
        else $error("[XCAP_REV] Revocation exceeded bounded cycle count");""")

        elif insn.name == "XCAP_CHK":
            props.append("""
    // ===================================================================
    // Capability Check after Revocation: Must fail
    // ===================================================================
    // Sequence property: REV followed by CHK on same cap must trap
    // (Requires multi-instruction sequence -- advanced riscv-formal)""")

    elif insn.unit == "trit":
        if insn.name == "XTRIT_ENC":
            props.append("""
    // ===================================================================
    // Encode/Decode Roundtrip: enc(dec(x)) == x (within range)
    // ===================================================================
    // Note: Requires paired test with XTRIT_DEC -- see sequence properties""")

        elif insn.name == "XTRIT_FFT":
            props.append("""
    // ===================================================================
    // FFT Butterfly: Output magnitude bounded
    // ===================================================================
    property p_fft_bounded;
        @(posedge clk) disable iff (!rst_n)
        insn_active && !rvfi_trap |->
            // Result magnitude should not exceed sum of input magnitudes
            // (Simplified -- full check requires fixed-point overflow analysis)
            (rvfi_rd_wdata != 64'hDEAD_DEAD_DEAD_DEAD);  // Sentinel for overflow
    endproperty
    assert property (p_fft_bounded)
        else $error("[XTRIT_FFT] Butterfly overflow detected");""")

    return "\n".join(props) if props else "    // No additional unit-specific properties for this instruction"


def generate_property_module(insn: XPlenumInsn) -> str:
    return PROPERTY_TEMPLATE.format(
        name=insn.name,
        name_lower=insn.name.lower(),
        mnemonic=insn.mnemonic,
        unit=insn.unit,
        opcode=insn.opcode,
        funct3=insn.funct3,
        funct7=insn.funct7,
        has_rd_cond="1'b1" if insn.has_rd else "1'b0",
        rd_property=gen_rd_property(insn),
        trap_property=gen_trap_property(insn),
        privilege_property=gen_privilege_property(insn),
        unit_specific_properties=gen_unit_specific(insn),
        description=insn.description,
    )


def generate_top_wrapper() -> str:
    instances = []
    for insn in XPLENUM_INSNS:
        instances.append(f"""
    rvfi_insn_{insn.name.lower()} u_{insn.name.lower()} (
        .clk(clk), .rst_n(rst_n),
        .rvfi_valid(rvfi_valid), .rvfi_order(rvfi_order),
        .rvfi_insn(rvfi_insn), .rvfi_trap(rvfi_trap),
        .rvfi_halt(rvfi_halt),
        .rvfi_rs1_addr(rvfi_rs1_addr), .rvfi_rs2_addr(rvfi_rs2_addr),
        .rvfi_rs1_rdata(rvfi_rs1_rdata), .rvfi_rs2_rdata(rvfi_rs2_rdata),
        .rvfi_rd_addr(rvfi_rd_addr), .rvfi_rd_wdata(rvfi_rd_wdata),
        .rvfi_pc_rdata(rvfi_pc_rdata), .rvfi_pc_wdata(rvfi_pc_wdata),
        .rvfi_mode(rvfi_mode)
    );""")

    return f"""\
// ===================================================================
// XPlenum riscv-formal Top-Level Property Wrapper
// Instantiates all 21 instruction property modules
// Generated by xplenum_rvfi_insn_gen.py -- Task 8A.1
// ===================================================================
`timescale 1ns/1ps

module xplenum_rvfi_props (
    input         clk,
    input         rst_n,
    input         rvfi_valid,
    input  [63:0] rvfi_order,
    input  [31:0] rvfi_insn,
    input         rvfi_trap,
    input         rvfi_halt,
    input  [4:0]  rvfi_rs1_addr,
    input  [4:0]  rvfi_rs2_addr,
    input  [63:0] rvfi_rs1_rdata,
    input  [63:0] rvfi_rs2_rdata,
    input  [4:0]  rvfi_rd_addr,
    input  [63:0] rvfi_rd_wdata,
    input  [63:0] rvfi_pc_rdata,
    input  [63:0] rvfi_pc_wdata,
    input  [1:0]  rvfi_mode
);
{"".join(instances)}

endmodule
"""


def main():
    parser = argparse.ArgumentParser(description="Generate XPlenum riscv-formal properties")
    parser.add_argument("--output-dir", default="formal/generated", help="Output directory")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    for insn in XPLENUM_INSNS:
        filepath = os.path.join(args.output_dir, f"rvfi_insn_{insn.name.lower()}.sv")
        with open(filepath, "w") as f:
            f.write(generate_property_module(insn))
        print(f"  Generated: {filepath}")

    wrapper_path = os.path.join(args.output_dir, "xplenum_rvfi_props.sv")
    with open(wrapper_path, "w") as f:
        f.write(generate_top_wrapper())
    print(f"  Generated: {wrapper_path}")

    print(f"\nTotal: {len(XPLENUM_INSNS)} instruction property modules + 1 wrapper")


if __name__ == "__main__":
    main()
