// Copyright (c) 2025-2026 Capomastro Holdings Ltd. (Canada)
// Patent(s) Pending — All Rights Reserved
// Applied Physics Division — Salvi Framework
// PROPRIETARY AND CONFIDENTIAL — All Rights Reserved

//! # EAC Ledger — Energy Attestation Continuous Statement of Account
//!
//! A pure-ternary, append-only, monotonically-non-decreasing ledger of
//! attested energy savings for a single PlenumNET kernel-resident node.
//!
//! ## Invariants
//!
//! - **L-1.** `total_saved_uj` only ever increases.
//! - **L-2.** `total_credited_uj` only ever increases.
//! - **L-3.** `total_credited_uj <= total_saved_uj` at all times.
//! - **L-4.** `balance_uj = total_saved_uj - total_credited_uj`.
//! - **L-5.** `last_atto` only ever increases (events are timestamp-ordered).
//! - **L-6.** Every accumulate / credit advances the running `chain_tag`,
//!   so any tampered, dropped, or reordered entry produces a different
//!   tag at the next read.
//!
//! ## Primary form
//!
//! The ledger renders itself as **Enhanced Markdown** via
//! [`LedgerStatement::render_enhanced_md`].  PDF / HTML / printed forms
//! are downstream conversions of that single canonical artefact.
//!
//! ## Encryption
//!
//! Statements are encrypted in pure ternary by a GF(3) stream cipher
//! whose keystream is generated by a (7, 11, 13)-coprime-triple lagged
//! recurrence over a 27-trit state — see [`encrypt_trits`].  The
//! `bridge`-gated convenience functions [`encrypt_md_to_packed`] and
//! [`decrypt_packed_to_md`] handle the byte-boundary at the rim of
//! the crate (no opaque-byte leak in default-feature paths).
//!
//! ## Unit ladder
//!
//! ```text
//!   1 ARC          ≡  1 kWh of attested savings
//!                  ≡  3 600 000 000 000 µJ      (= 3.6 × 10¹² µJ)
//!   1 µARC         ≡  3 600 000 µJ              (= 3.6 × 10⁶  µJ)
//!   1 XRP          ≡  1 000 000 drops
//!   balance_µARC   =  balance_µJ ÷ 3 600 000
//!   balance_drops  =  balance_µJ × USD_µ_per_kWh
//!                       ÷ (3 600 000 × USD_µ_per_XRP)
//! ```
//!
//! All ledger arithmetic is done in `u128` integer space — no float
//! ever appears on the wire or in the totals.

use alloc::string::String;
use alloc::vec::Vec;
use core::fmt::Write as _;

use crate::trit::Trit;
use crate::tritvec::TritVec;

// ════════════════════════════════════════════════════════════════════════
// Unit constants
// ════════════════════════════════════════════════════════════════════════

/// Microjoules per kilowatt-hour: `1 kWh = 3.6 × 10¹² µJ`.
pub const UJ_PER_KWH: u128 = 3_600_000_000_000;

/// Microjoules per micro-ARC token: `1 µARC = 3.6 × 10⁶ µJ`.
///
/// Equivalently, `1 ARC = 1 kWh = 10⁶ µARC = UJ_PER_KWH µJ`.
pub const UJ_PER_MICRO_ARC: u128 = 3_600_000;

/// Drops per XRP (XRPL atomic unit): `1 XRP = 10⁶ drops`.
pub const DROPS_PER_XRP: u128 = 1_000_000;

// ════════════════════════════════════════════════════════════════════════
// Ledger entry
// ════════════════════════════════════════════════════════════════════════

/// A single ledger event.  Either an accumulation of savings
/// (`saved_uj_delta > 0, credited_uj_delta == 0`) or a credit
/// (`saved_uj_delta == 0, credited_uj_delta > 0`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LedgerEntry {
    /// UTC-grounded attoseconds since the Unix epoch at the moment
    /// of the event.  Strictly monotonically non-decreasing across
    /// the entry sequence.
    pub atto_at_event: u128,
    /// Microjoules accumulated by this entry (0 for credit entries).
    pub saved_uj_delta: u64,
    /// Microjoules credited by this entry (0 for accumulate entries).
    pub credited_uj_delta: u64,
}

// ════════════════════════════════════════════════════════════════════════
// Pricing anchors — caller-supplied, no hard-coded market data
// ════════════════════════════════════════════════════════════════════════

/// Pricing anchors for the ARC ↔ XRP conversion view.
///
/// Both quantities are in **micro-USD** (10⁻⁶ USD) so the entire
/// conversion stays in integer space.  E.g. `$0.10 / kWh` is encoded
/// as `usd_per_kwh_micro = 100_000`; `$2.20 / XRP` is encoded as
/// `usd_per_xrp_micro = 2_200_000`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Pricing {
    pub usd_per_kwh_micro: u64,
    pub usd_per_xrp_micro: u64,
}

impl Pricing {
    /// Reasonable default anchors used in PlenumNET reference docs:
    /// US industrial-blend electricity at $0.10 / kWh and XRP at $2.20.
    pub const fn reference() -> Self {
        Self {
            usd_per_kwh_micro: 100_000,
            usd_per_xrp_micro: 2_200_000,
        }
    }
}

// ════════════════════════════════════════════════════════════════════════
// LedgerStatement — the running statement of account
// ════════════════════════════════════════════════════════════════════════

/// A continuous statement of account for a single PlenumNET node.
///
/// Owned by the kernel's EAC subsystem.  Persists across reboots
/// (the kernel rehydrates `genesis_atto`, totals, and `chain_tag`
/// from a sealed on-disk record; `entries` may be truncated for
/// disk-space but the chain tag still proves continuity).
#[derive(Debug, Clone)]
pub struct LedgerStatement {
    /// Attoseconds since UTC epoch at which the ledger was opened
    /// (the node's first-ever boot of the EAC kernel module).
    pub genesis_atto: u128,
    /// Lifetime total of attested savings, in microjoules.
    pub total_saved_uj: u128,
    /// Lifetime total of credited (redeemed / spent) savings, in µJ.
    pub total_credited_uj: u128,
    /// Atto timestamp of the most recent event (or `genesis_atto`
    /// if no events yet).
    pub last_atto: u128,
    /// Append-only event log.  May be checkpointed and truncated
    /// by the kernel; the running `chain_tag` is the canonical
    /// integrity witness.
    pub entries: Vec<LedgerEntry>,
    /// 81-trit running sponge tag covering every event ever absorbed.
    pub chain_tag: TritVec,
}

impl LedgerStatement {
    /// Open a new ledger at the given UTC-attosecond genesis instant.
    pub fn new(genesis_atto: u128) -> Self {
        Self {
            genesis_atto,
            total_saved_uj: 0,
            total_credited_uj: 0,
            last_atto: genesis_atto,
            entries: Vec::new(),
            chain_tag: TritVec::zeros(81),
        }
    }

    /// Re-open a ledger from sealed totals — used by the kernel to
    /// rehydrate a previously-checkpointed statement after a reboot.
    pub fn rehydrate(
        genesis_atto: u128,
        total_saved_uj: u128,
        total_credited_uj: u128,
        last_atto: u128,
        chain_tag: TritVec,
    ) -> Self {
        Self {
            genesis_atto,
            total_saved_uj,
            total_credited_uj,
            last_atto,
            entries: Vec::new(),
            chain_tag,
        }
    }

    /// Accumulate `saved_uj_delta` microjoules of attested savings at
    /// UTC-attosecond `atto`.  Strictly monotonic; rejects out-of-order
    /// events.
    pub fn accumulate(
        &mut self,
        saved_uj_delta: u64,
        atto: u128,
    ) -> Result<(), &'static str> {
        if atto < self.last_atto {
            return Err("LedgerStatement::accumulate: non-monotonic atto");
        }
        self.total_saved_uj = self
            .total_saved_uj
            .saturating_add(saved_uj_delta as u128);
        self.last_atto = atto;
        self.entries.push(LedgerEntry {
            atto_at_event: atto,
            saved_uj_delta,
            credited_uj_delta: 0,
        });
        self.advance_chain_tag(saved_uj_delta, 0);
        Ok(())
    }

    /// Credit (redeem / spend) `credited_uj` microjoules against the
    /// outstanding balance at UTC-attosecond `atto`.  Refuses to
    /// over-credit (balance can never go negative).
    pub fn credit(
        &mut self,
        credited_uj: u64,
        atto: u128,
    ) -> Result<(), &'static str> {
        if atto < self.last_atto {
            return Err("LedgerStatement::credit: non-monotonic atto");
        }
        let new_credited = self
            .total_credited_uj
            .saturating_add(credited_uj as u128);
        if new_credited > self.total_saved_uj {
            return Err("LedgerStatement::credit: would exceed saved balance");
        }
        self.total_credited_uj = new_credited;
        self.last_atto = atto;
        self.entries.push(LedgerEntry {
            atto_at_event: atto,
            saved_uj_delta: 0,
            credited_uj_delta: credited_uj,
        });
        self.advance_chain_tag(0, credited_uj);
        Ok(())
    }

    /// Outstanding balance, in microjoules.
    #[inline]
    pub fn balance_uj(&self) -> u128 {
        self.total_saved_uj.saturating_sub(self.total_credited_uj)
    }

    /// Outstanding balance, in micro-ARC (10⁻⁶ ARC) — exact integer.
    #[inline]
    pub fn balance_micro_arc(&self) -> u128 {
        self.balance_uj() / UJ_PER_MICRO_ARC
    }

    /// Outstanding balance, in XRP drops (10⁻⁶ XRP) — exact integer.
    ///
    /// Returns 0 if `pricing.usd_per_xrp_micro == 0` (defensive).
    #[inline]
    pub fn balance_drops(&self, pricing: &Pricing) -> u128 {
        if pricing.usd_per_xrp_micro == 0 {
            return 0;
        }
        let bal = self.balance_uj();
        // drops = bal_µJ × USD_µ_per_kWh
        //         ÷ (3 600 000 × USD_µ_per_XRP)
        bal.saturating_mul(pricing.usd_per_kwh_micro as u128)
            / (UJ_PER_MICRO_ARC * pricing.usd_per_xrp_micro as u128)
    }

    /// Fold a (saved, credited) delta into the running 81-trit chain
    /// tag.  Pure GF(3) absorption — every entry permutes the tag
    /// deterministically, so any tamper, drop, or reorder is detected
    /// at the next read of `chain_tag`.
    fn advance_chain_tag(&mut self, saved: u64, credited: u64) {
        let len = self.chain_tag.len();
        if len == 0 {
            return;
        }
        // Combine the deltas with the latest atto into a u128 mixer.
        let mut acc: u128 = (saved as u128)
            .wrapping_add((credited as u128).wrapping_mul(7))
            .wrapping_add(self.last_atto.wrapping_mul(13))
            .wrapping_add(0x9E37_79B9_7F4A_7C15_F39C_C060_5CED_C835u128);
        let slice = self.chain_tag.as_mut_slice();
        for i in 0..len {
            let d = (acc % 3) as u8;
            let cur = slice[i].value_b();
            // GF(3) add the mixer trit into the tag trit.
            slice[i] = Trit::from_b((cur + d) % 3).unwrap_or(Trit::One);
            // Advance the mixer with a coprime-multiplier sweep.
            acc = acc.wrapping_mul(11).wrapping_add(13);
            if (i % 27) == 26 {
                acc ^= self.last_atto.rotate_left((i as u32 + 7) & 63);
            }
        }
    }

    // ───────────────────────────────────────────────────────────────────
    // Enhanced Markdown rendering — the canonical primary form
    // ───────────────────────────────────────────────────────────────────

    /// Render the ledger as Enhanced Markdown.  This is the
    /// **canonical primary form** of the EAC; PDF / HTML / printed
    /// versions are downstream conversions of this string.
    ///
    /// Enhanced features used:
    /// - GFM tables with right-aligned numeric columns
    /// - Fenced code blocks with language hints (`trit-rep-c`, `math`)
    /// - YAML front-matter for downstream renderers
    /// - Anchor IDs on H2 sections for cross-linking
    pub fn render_enhanced_md(&self, node_id: &str, pricing: &Pricing) -> String {
        let bal_uj = self.balance_uj();
        let bal_marc = self.balance_micro_arc();
        let bal_arc_int = bal_marc / 1_000_000;
        let bal_arc_frac = bal_marc % 1_000_000;
        let drops = self.balance_drops(pricing);
        let xrp_int = drops / DROPS_PER_XRP;
        let xrp_frac = drops % DROPS_PER_XRP;
        let entries_n = self.entries.len();
        let chain_tag_repc = trits_to_rep_c_string(&self.chain_tag);
        let tenure_atto = self.last_atto.saturating_sub(self.genesis_atto);

        // Pricing displayed as integer-USD-cents and integer-USD-and-cents
        // for human friendliness; underlying math stayed integer.
        let kwh_usd_int = (pricing.usd_per_kwh_micro / 1_000_000) as u128;
        let kwh_usd_frac = (pricing.usd_per_kwh_micro % 1_000_000) as u128;
        let xrp_usd_int = (pricing.usd_per_xrp_micro / 1_000_000) as u128;
        let xrp_usd_frac = (pricing.usd_per_xrp_micro % 1_000_000) as u128;

        let mut s = String::with_capacity(4096);

        // ── YAML front-matter ──
        let _ = writeln!(s, "---");
        let _ = writeln!(s, "doc_kind: eac-statement-of-account");
        let _ = writeln!(s, "doc_version: 1");
        let _ = writeln!(s, "node_id: \"{}\"", node_id);
        let _ = writeln!(s, "genesis_atto: {}", self.genesis_atto);
        let _ = writeln!(s, "last_atto: {}", self.last_atto);
        let _ = writeln!(s, "tenure_atto: {}", tenure_atto);
        let _ = writeln!(s, "entries: {}", entries_n);
        let _ = writeln!(s, "total_saved_uj: {}", self.total_saved_uj);
        let _ = writeln!(s, "total_credited_uj: {}", self.total_credited_uj);
        let _ = writeln!(s, "balance_uj: {}", bal_uj);
        let _ = writeln!(s, "balance_micro_arc: {}", bal_marc);
        let _ = writeln!(s, "balance_drops_xrp: {}", drops);
        let _ = writeln!(
            s,
            "pricing: {{ usd_per_kwh_micro: {}, usd_per_xrp_micro: {} }}",
            pricing.usd_per_kwh_micro, pricing.usd_per_xrp_micro
        );
        let _ = writeln!(s, "---");
        let _ = writeln!(s);

        // ── H1 ──
        let _ = writeln!(s, "# Energy Attestation Certificate");
        let _ = writeln!(s, "## Continuous Statement of Account · PlenumNET Ledger");
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "_Issued by node `{}` · monotonic, append-only, GF(3)-tag-sealed._",
            node_id
        );
        let _ = writeln!(s);

        // ── Section: Identity ──
        let _ = writeln!(s, "## Identity & Tenure {{#identity}}");
        let _ = writeln!(s);
        let _ = writeln!(s, "| Field | Value |");
        let _ = writeln!(s, "|---|---|");
        let _ = writeln!(s, "| Node ID | `{}` |", node_id);
        let _ = writeln!(s, "| Genesis (atto since UTC epoch) | `{}` |", self.genesis_atto);
        let _ = writeln!(s, "| Last event (atto since UTC epoch) | `{}` |", self.last_atto);
        let _ = writeln!(s, "| Tenure since genesis (atto) | `{}` |", tenure_atto);
        let _ = writeln!(s, "| Cumulative entries | `{}` |", entries_n);
        let _ = writeln!(s);

        // ── Section: Ledger totals ──
        let _ = writeln!(s, "## Ledger Totals {{#totals}}");
        let _ = writeln!(s);
        let _ = writeln!(s, "| Quantity | Value | Unit |");
        let _ = writeln!(s, "|---|---:|---|");
        let _ = writeln!(
            s,
            "| Total **saved** since genesis | `{}` | µJ |",
            self.total_saved_uj
        );
        let _ = writeln!(
            s,
            "| Total **credited** since genesis | `{}` | µJ |",
            self.total_credited_uj
        );
        let _ = writeln!(s, "| **Outstanding balance** | `{}` | µJ |", bal_uj);
        let _ = writeln!(
            s,
            "| **Outstanding balance** | `{}.{:06}` | ARC |",
            bal_arc_int, bal_arc_frac
        );
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "_Balance can only ever increase unless an operator submits a signed credit transaction; it can never go negative._"
        );
        let _ = writeln!(s);

        // ── Section: XRP equivalent ──
        let _ = writeln!(s, "## XRP Equivalent {{#xrp}}");
        let _ = writeln!(s);
        let _ = writeln!(s, "Pricing anchors (caller-supplied, no hard-coded market data):");
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "- Electricity: `{}.{:06}` USD / kWh",
            kwh_usd_int, kwh_usd_frac
        );
        let _ = writeln!(
            s,
            "- XRP spot:    `{}.{:06}` USD / XRP",
            xrp_usd_int, xrp_usd_frac
        );
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "**Balance in XRP:** `{}.{:06}` XRP  (`{}` drops)",
            xrp_int, xrp_frac, drops
        );
        let _ = writeln!(s);

        // ── Section: Chain tag ──
        let _ = writeln!(s, "## Chain Tag {{#chain-tag}}");
        let _ = writeln!(s);
        let _ = writeln!(s, "81-trit GF(3) running tag absorbing every event since genesis.");
        let _ = writeln!(s, "Any tamper, drop, or reorder of an entry permutes this value.");
        let _ = writeln!(s);
        let _ = writeln!(s, "```trit-rep-c");
        let _ = writeln!(s, "{}", chain_tag_repc);
        let _ = writeln!(s, "```");
        let _ = writeln!(s);

        // ── Section: Conversion formula ──
        let _ = writeln!(s, "## Conversion Formula {{#formula}}");
        let _ = writeln!(s);
        let _ = writeln!(s, "```math");
        let _ = writeln!(s, "1 ARC          ≡  1 kWh saved");
        let _ = writeln!(s, "               ≡  3.6 × 10¹² µJ");
        let _ = writeln!(s, "balance_µARC   =  balance_µJ ÷ 3 600 000");
        let _ = writeln!(s, "balance_drops  =  balance_µJ × USD_µ_per_kWh");
        let _ = writeln!(s, "                  ÷ (3 600 000 × USD_µ_per_XRP)");
        let _ = writeln!(s, "```");
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "_All ledger arithmetic is `u128` integer; no float ever appears on the wire or in the totals._"
        );

        s
    }
}

// ════════════════════════════════════════════════════════════════════════
// Helpers
// ════════════════════════════════════════════════════════════════════════

/// Render a `TritVec` as a Rep-C base-3 string over the alphabet `{1,2,3}`.
pub fn trits_to_rep_c_string(v: &TritVec) -> String {
    let slice = v.as_slice();
    let mut s = String::with_capacity(slice.len());
    for t in slice {
        let c = match t {
            Trit::One => '1',
            Trit::Two => '2',
            Trit::Three => '3',
        };
        s.push(c);
    }
    s
}

/// Parse a Rep-C base-3 string (alphabet `{1,2,3}`) into a `TritVec`.
/// Returns `None` if any character is outside the alphabet.
pub fn rep_c_string_to_trits(s: &str) -> Option<TritVec> {
    let mut out = Vec::with_capacity(s.len());
    for c in s.chars() {
        let t = match c {
            '1' => Trit::One,
            '2' => Trit::Two,
            '3' => Trit::Three,
            _ => return None,
        };
        out.push(t);
    }
    Some(TritVec::from_trits(&out))
}

// ════════════════════════════════════════════════════════════════════════
// Pure-ternary GF(3) stream cipher
// ════════════════════════════════════════════════════════════════════════

/// Encrypt a plaintext `TritVec` with a `TritVec` key under a pure
/// GF(3) stream cipher.  See module docs for the keystream construction.
pub fn encrypt_trits(pt: &TritVec, key: &TritVec) -> TritVec {
    let n = pt.len();
    if n == 0 || key.is_empty() {
        return pt.clone();
    }
    let ks = expand_keystream(key, n);
    let pt_slice = pt.as_slice();
    let ks_slice = ks.as_slice();
    let mut out = Vec::with_capacity(n);
    for i in 0..n {
        let pv = pt_slice[i].value_b();
        let kv = ks_slice[i].value_b();
        out.push(Trit::from_b((pv + kv) % 3).unwrap_or(Trit::One));
    }
    TritVec::from_trits(&out)
}

/// Decrypt a ciphertext `TritVec` with a `TritVec` key.  Inverse of
/// [`encrypt_trits`].
pub fn decrypt_trits(ct: &TritVec, key: &TritVec) -> TritVec {
    let n = ct.len();
    if n == 0 || key.is_empty() {
        return ct.clone();
    }
    let ks = expand_keystream(key, n);
    let ct_slice = ct.as_slice();
    let ks_slice = ks.as_slice();
    let mut out = Vec::with_capacity(n);
    for i in 0..n {
        let cv = ct_slice[i].value_b();
        let kv = ks_slice[i].value_b();
        out.push(Trit::from_b((3 + cv - kv) % 3).unwrap_or(Trit::One));
    }
    TritVec::from_trits(&out)
}

/// Expand a key TritVec to a `want`-trit keystream using a 27-trit
/// state and the (7, 11, 13) coprime-triple lagged GF(3) recurrence:
///
/// ```text
///   state[i] = (state[i-7] + state[i-11] + state[i-13]) mod 3   (i ≥ 27)
/// ```
///
/// The first 27 trits of the state are seeded by cycling the key
/// through three coprime-indexed taps so short keys still distribute
/// across the full state.
fn expand_keystream(key: &TritVec, want: usize) -> TritVec {
    let key_len = key.len();
    let key_slice = key.as_slice();
    let state_len = 27usize;
    let total = if want < state_len { state_len } else { want };
    let mut state: Vec<Trit> = Vec::with_capacity(total);

    // Seed first 27 trits.
    for i in 0..state_len {
        let k = key_slice[i % key_len].value_b();
        let mix_a = key_slice[(i.wrapping_mul(7)) % key_len].value_b();
        let mix_b = key_slice[(i.wrapping_mul(11)) % key_len].value_b();
        state.push(Trit::from_b((k + mix_a + mix_b) % 3).unwrap_or(Trit::One));
    }

    // Lagged recurrence.
    for i in state_len..want {
        let a = state[i - 7].value_b();
        let b = state[i - 11].value_b();
        let c = state[i - 13].value_b();
        state.push(Trit::from_b((a + b + c) % 3).unwrap_or(Trit::One));
    }

    state.truncate(want);
    TritVec::from_trits(&state)
}

// ════════════════════════════════════════════════════════════════════════
// `bridge`-feature: byte-boundary conveniences
// ════════════════════════════════════════════════════════════════════════

#[cfg(feature = "bridge")]
pub mod bridged {
    //! Byte-boundary helpers gated behind `feature = "bridge"`.
    //!
    //! These are the **only** functions in `eac_ledger` that touch
    //! opaque bytes; the pure ternary path stays no_std + alloc clean.

    use super::{decrypt_trits, encrypt_trits};
    use crate::bridge::{from_bytes_packed, to_bytes_packed};
    use crate::tritvec::TritVec;
    use alloc::string::String;
    use alloc::vec::Vec;

    /// Encrypt a Markdown statement of account (UTF-8 string) under a
    /// trit key, returning packed-base-3 ciphertext bytes.
    pub fn encrypt_md_to_packed(md: &str, key: &TritVec) -> Vec<u8> {
        // Convert MD bytes → TritVec via the canonical packed-base-3 codec.
        let pt = match from_bytes_packed(md.as_bytes()) {
            Some(v) => v,
            None => return Vec::new(),
        };
        let ct = encrypt_trits(&pt, key);
        to_bytes_packed(&ct)
    }

    /// Inverse of [`encrypt_md_to_packed`].  Returns `None` if the
    /// recovered byte string is not valid UTF-8 (e.g. wrong key).
    pub fn decrypt_packed_to_md(ct_bytes: &[u8], key: &TritVec) -> Option<String> {
        let ct = from_bytes_packed(ct_bytes)?;
        let pt = decrypt_trits(&ct, key);
        let bytes = to_bytes_packed(&pt);
        String::from_utf8(bytes).ok()
    }
}

// ════════════════════════════════════════════════════════════════════════
// Tests
// ════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ledger_monotonic_accumulate() {
        let mut l = LedgerStatement::new(0);
        l.accumulate(15_252_000, 1).unwrap();
        l.accumulate(8_928_000_000_000, 86_400_000_000_000_000_000_000).unwrap();
        assert_eq!(l.total_saved_uj, 15_252_000 + 8_928_000_000_000);
        assert_eq!(l.balance_uj(), l.total_saved_uj);
    }

    #[test]
    fn ledger_rejects_non_monotonic_atto() {
        let mut l = LedgerStatement::new(0);
        l.accumulate(100, 10).unwrap();
        assert!(l.accumulate(100, 5).is_err());
    }

    #[test]
    fn credit_cannot_exceed_saved() {
        let mut l = LedgerStatement::new(0);
        l.accumulate(100, 1).unwrap();
        assert!(l.credit(50, 2).is_ok());
        assert_eq!(l.balance_uj(), 50);
        assert!(l.credit(100, 3).is_err());
        assert_eq!(l.balance_uj(), 50);
    }

    #[test]
    fn balance_arc_and_xrp_exact_integer() {
        let mut l = LedgerStatement::new(0);
        // 8.928 kWh = 8.928 × 3.6e12 µJ = 32_140_800_000_000 µJ
        l.accumulate(32_140_800_000_000u64, 1).unwrap();
        assert_eq!(l.balance_micro_arc(), 8_928_000); // = 8.928 ARC

        let pricing = Pricing::reference(); // $0.10/kWh, $2.20/XRP
        // drops = 32_140_800_000_000 × 100_000 / (3_600_000 × 2_200_000)
        //       = 3_214_080_000_000_000_000 / 7_920_000_000_000
        //       = 405_818
        assert_eq!(l.balance_drops(&pricing), 405_818);
    }

    #[test]
    fn chain_tag_changes_on_every_entry() {
        let mut l = LedgerStatement::new(0);
        let t0 = trits_to_rep_c_string(&l.chain_tag);
        l.accumulate(100, 1).unwrap();
        let t1 = trits_to_rep_c_string(&l.chain_tag);
        l.accumulate(100, 2).unwrap();
        let t2 = trits_to_rep_c_string(&l.chain_tag);
        assert_ne!(t0, t1);
        assert_ne!(t1, t2);
    }

    #[test]
    fn enhanced_md_contains_canonical_sections() {
        let mut l = LedgerStatement::new(0);
        l.accumulate(32_140_800_000_000u64, 1).unwrap();
        let md = l.render_enhanced_md("tdns:hmodal-demo:01", &Pricing::reference());
        assert!(md.starts_with("---"));
        assert!(md.contains("doc_kind: eac-statement-of-account"));
        assert!(md.contains("# Energy Attestation Certificate"));
        assert!(md.contains("## Ledger Totals"));
        assert!(md.contains("## XRP Equivalent"));
        assert!(md.contains("## Chain Tag"));
        assert!(md.contains("8.928000")); // ARC balance
        assert!(md.contains("0.405818")); // XRP balance
        assert!(md.contains("```trit-rep-c"));
        assert!(md.contains("```math"));
    }

    #[test]
    fn cipher_roundtrips_pure_ternary() {
        let pt = rep_c_string_to_trits(
            "1231231232132133221231231232132132133211231231232132132133",
        )
        .unwrap();
        let key = rep_c_string_to_trits("21311232313").unwrap();
        let ct = encrypt_trits(&pt, &key);
        let recovered = decrypt_trits(&ct, &key);
        assert!(pt.equal_values(&recovered));
        // Ciphertext must not equal plaintext (vanishingly unlikely otherwise).
        assert!(!pt.equal_values(&ct));
    }

    #[test]
    fn cipher_wrong_key_yields_different_plaintext() {
        let pt = rep_c_string_to_trits("12312312321321332").unwrap();
        let key_a = rep_c_string_to_trits("213").unwrap();
        let key_b = rep_c_string_to_trits("312").unwrap();
        let ct = encrypt_trits(&pt, &key_a);
        let bad = decrypt_trits(&ct, &key_b);
        assert!(!pt.equal_values(&bad));
    }
}
