// Copyright (c) 2025-2026 Capomastro Holdings Ltd. (Canada)
// Patent(s) Pending — All Rights Reserved
// Applied Physics Division — Salvi Framework
// PROPRIETARY AND CONFIDENTIAL — All Rights Reserved

//! # `generating_system` — the unifying quadratic
//!
//! The Salvi Framework is generated by the single quadratic
//!
//! ```text
//!     arc² − 832·arc + 118300 = 0
//! ```
//!
//! whose roots are exactly `ARC = 182` and its complement
//! `arc₂ = 650`. The discriminant is the sponge constant
//! `Δ_sponge = b⁶ = 729`, and `√Δ_sponge = b³ = 27`.
//!
//! ## Invariants verified at compile time
//!
//! - **I-12.** `Δ = 1 + 4·ARC = b⁶`, `√Δ = b³`. (Re-asserted here for
//!   the generating-system axis specifically — the canonical pin lives
//!   in [`crate::constants`].)
//! - **I-18.** Vieta's formulas pin the (`ARC`, `arc₂`) pair:
//!   `ARC + arc₂ = 832`,   `ARC · arc₂ = 118300`.

use crate::constants::{ARC_COMP_INT, ARC_INT, B3_INT, B6_INT, DELTA_SPONGE_INT};

/// Sum-of-roots coefficient `−B/A = 832`.
pub const SUM_OF_ROOTS: u64 = 832;
/// Product-of-roots constant `C/A = 118300`.
pub const PRODUCT_OF_ROOTS: u64 = 118300;

/// Evaluate the generating polynomial at `x`. Returns `0` for the two
/// canonical roots `(ARC, arc₂)`.
pub const fn poly(x: u64) -> i128 {
    (x as i128) * (x as i128) - (SUM_OF_ROOTS as i128) * (x as i128) + (PRODUCT_OF_ROOTS as i128)
}

const _: () = {
    // I-12 sponge discriminant pin
    assert!(DELTA_SPONGE_INT == B6_INT);
    assert!(B3_INT * B3_INT == B6_INT);

    // I-18 Vieta — ARC and arc₂ are the roots
    assert!(ARC_INT + ARC_COMP_INT == SUM_OF_ROOTS);
    assert!(ARC_INT * ARC_COMP_INT == PRODUCT_OF_ROOTS);
    // Polynomial vanishes at both roots
    assert!(poly(ARC_INT) == 0);
    assert!(poly(ARC_COMP_INT) == 0);
};
