// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/coprime-projection/CoprimeProjection.tsx": () => import("../components/mockups/coprime-projection/CoprimeProjection.tsx"),
  "./components/mockups/capomastro364/Capomastro364.tsx": () => import("../components/mockups/capomastro364/Capomastro364.tsx")
};
