/**
 * Copyright (c) 2025-2026 Capomastro Holdings Ltd. (Canada)
 * Patent(s) Pending — All Rights Reserved
 * Applied Physics Division
 *
 * SINGLE SOURCE OF TRUTH — Platform-wide constants.
 * Update numbers here and they propagate to frontend, backend, and docs endpoints.
 */

export const PLATFORM = {
  VM_OPCODES: 176,
  VM_ISA_VERSION: "v2.1",
  VM_ISA_PREV_VERSION: "v2.0",
  VM_ISA_PREV_OPCODES: 160,
  VM_ISA_V1_OPCODES: 62,
  VM_REGISTERS: 27,
  API_ENDPOINTS: 279,
  API_SERVICES: 23,
  API_DOMAIN_GROUPS: 7,
  KERNEL_LOC: "47,000+",
  KERNEL_SUBSYSTEMS: 14,
  KERNEL_BINARY_SIZE: "33 MB",
  TESTS_PASSING: "1,901",
  DENSITY_ADVANTAGE: 59,
  PLATFORM_VERSION: "2.3.2",

  BENCH_TL_DSA_44_US: "1,220",
  BENCH_TL_DSA_65_US: "1,700",
  BENCH_TL_DSA_87_US: "2,470",
  BENCH_TL_DSA_87_SPEEDUP: "5.9",
  BENCH_ALU_PARITY: "1.06",
  BENCH_RING_MUL_RATIO: "0.59",
  BENCH_TRIT_PACK_NS: "31",
  BENCH_REP_CONVERT_NS: "0.7",
  BENCH_KEM_ROUNDTRIP_MS: "3.4",
  BENCH_KANI_PROOFS: 50,

  HYPERCUBE_DIMENSIONS: 13,
  HYPERCUBE_VERTICES: "1,594,323",
  TDNS_ADDRESS_SPACE: "68.63 trillion",
  TDNS_TRITS: 27,
  HYPERCUBE_NEIGHBORS: 26,
  INTER_CUBE_TESTS: 97,
  INTER_CUBE_ENDPOINTS: 11,
  INTER_CUBE_SERVICES: 4,
  INTER_CUBE_ROUTING_TABLES: 0,
  MILESTONES: 42,
} as const;

export type Platform = typeof PLATFORM;
