// Copyright (c) 2025-2026 Capomastro Holdings Ltd. (Canada)
// Patent(s) Pending — All Rights Reserved
// Applied Physics Division
//
// PROPRIETARY AND CONFIDENTIAL
// All Rights Reserved.
//
// This file is part of the Salvi Framework / PlenumNET platform.
// Unauthorized copying, modification, distribution, or use of this file,
// via any medium, is strictly prohibited without the prior written
// permission of Capomastro Holdings Ltd.
//
// See LICENSE in the repository root for full terms.

//! # Unified Public Constants — Salvi Framework
//!
//! The **singular set of shared constants** for all ternary mathematics modules.
//! Every module in `ternary-math` imports its fundamental values from here —
//! no module defines its own copy. This guarantees consistency across:
//!
//! - `ternary_circle` (Z₂₈ geometry)
//! - `tribonacci` (base-3 recurrence)
//! - `borromean` (three-party topology)
//! - `clifford` (Cl(3,0)/GF(3) gate compression)
//! - `torus` (ternary torus network topology)
//!
//! ## Design Principle
//!
//! All constants derive from two axioms:
//!   1. A full circle is **364 degrees** = `111111₃` (six-digit base-3 repunit).
//!   2. The Tribonacci constant **τ ≈ 1.839** is the real root of x³ = x² + x + 1.
//!
//! Everything else — π = 14, 1 radian = 13°, Z₂₈ cyclic group — follows.

use std::f64::consts::PI as STD_PI;

// ══════════════════════════════════════════════════════════════
// TERNARY CIRCLE — ANGULAR SYSTEM
// ══════════════════════════════════════════════════════════════

/// Full circle in the ternary angular system: **364 degrees**.
///
/// In base 3: `111111₃` = (3⁶ − 1) / 2 = 364.
/// This is a **six-digit repunit** — the circle IS a base-3 repunit.
pub const FULL_CIRCLE_DEG: f64 = 364.0;

/// Full circle as a base-3 repunit string.
pub const FULL_CIRCLE_BASE3: &str = "111111";

/// π in the ternary circle system: **exactly 14**.
///
/// This is the ratio of circumference to diameter in the ternary geometry.
/// 14 = 112₃ in base 3.
pub const PI_TERNARY: f64 = 14.0;

/// 2π in the ternary system: **28**.
///
/// A full circle is 28 ternary radians.
/// 28 = 1001₃ in base 3.
pub const TWO_PI_TERNARY: f64 = 28.0;

/// One ternary radian in degrees: **exactly 13°**.
///
/// 13 = `111₃`, a three-digit base-3 repunit.
/// 13 is also T₇, the seventh Tribonacci number.
/// The radian is simultaneously a Tribonacci number and a ternary repunit.
pub const RADIAN_DEG: f64 = 13.0;

/// One ternary radian as a base-3 repunit string.
pub const RADIAN_BASE3: &str = "111";

// ══════════════════════════════════════════════════════════════
// Z₂₈ CYCLIC GROUP
// ══════════════════════════════════════════════════════════════

/// Order of the cyclic group Z₂₈ generated by the ternary radian.
///
/// The set {0·13°, 1·13°, 2·13°, …, 27·13°} modulo 364° cycles through
/// exactly 28 distinct positions before returning to the origin.
pub const CYCLIC_ORDER: u32 = 28;

/// Number of ternary radians in a full circle (= CYCLIC_ORDER).
pub const RADIANS_PER_CIRCLE: u32 = 28;

/// Number of dimensions in the Tribonacci 28-Dimension Symmetry.
///
/// The Z₂₈ cyclic group partitions the circle into 28 sectors of 13° each.
pub const Z28_DIMENSIONS: u32 = 28;

/// The generator of Z₂₈ — the angular step of 1 ternary radian (13°).
pub const Z28_GENERATOR: u32 = 1;

/// The co-generator: 13 radians maps back to 1° short of full coverage,
/// and 13 is itself the radian value. gcd(13, 28) = 1 so 13 also generates Z₂₈.
pub const Z28_CO_GENERATOR: u32 = 13;

// ══════════════════════════════════════════════════════════════
// TRIBONACCI CONSTANTS
// ══════════════════════════════════════════════════════════════

/// The Tribonacci constant τ ≈ 1.839286755214161.
///
/// Real root of x³ = x² + x + 1. The native irrational of ternary
/// recursion, analogous to φ in binary/Fibonacci systems.
pub const TAU_TRIBONACCI: f64 = 1.839286755214161;

/// τ² ≈ 3.38297576790891.
pub const TAU_SQUARED: f64 = 3.38297576790891;

/// τ³ = τ² + τ + 1 ≈ 6.22226252312307.
pub const TAU_CUBED: f64 = 6.22226252312307;

/// Tribonacci golden angle (native ternary): 364° / τ³ ≈ 58.50°.
///
/// The smallest irrational rotation derived from τ that yields optimal
/// aperiodic packing in the ternary circle — the analogue of the golden
/// angle (360°/φ²) in phyllotaxis.
pub const TRIBONACCI_GOLDEN_ANGLE_DEG: f64 = 58.50438656;

/// Classical golden angle translated into the ternary circle:
/// 364° / φ² where φ = (1+√5)/2.
///
/// Factors as 2 · 7 · 13 · (3 − √5)°, where 2, 7, 13 are Tribonacci numbers.
pub const GOLDEN_ANGLE_TERNARY_DEG: f64 = 138.98056;

/// Maximum number of trits supported for Tribonacci computations.
/// Covers T(n) up to n ≈ 200.
pub const MAX_TRITS: usize = 128;

// ══════════════════════════════════════════════════════════════
// WALK INSTRUCTION SET ON Z₂₈
// ══════════════════════════════════════════════════════════════

/// Walk instruction for trit digit 0: **0 radians** (no turn, step forward).
pub const WALK_TURN_0: f64 = 0.0;

/// Walk instruction for trit digit 1: **1 ternary radian = 13°**.
pub const WALK_TURN_1: f64 = 13.0;

/// Walk instruction for trit digit 2: **2 ternary radians = 26°**.
pub const WALK_TURN_2: f64 = 26.0;

// ══════════════════════════════════════════════════════════════
// CLIFFORD ALGEBRA DIMENSIONAL CONSTANTS
// ══════════════════════════════════════════════════════════════

/// Number of basis vectors in Cl(3,0)/GF(3).
pub const CLIFFORD_GENERATORS: usize = 3;

/// Total dimension of the algebra: 2^3 = 8 components.
pub const CLIFFORD_DIM: usize = 8;

/// Number of even-grade basis elements (scalar + bivectors = 4).
pub const CLIFFORD_EVEN_DIM: usize = 4;

// ══════════════════════════════════════════════════════════════
// TORUS TOPOLOGY CONSTANTS
// ══════════════════════════════════════════════════════════════

/// The ternary radix for the torus k-ary n-cube (k=3).
pub const TORUS_RADIX: u32 = 3;

/// The number of neighbors per dimension on the torus (forward + backward).
pub const TORUS_NEIGHBORS_PER_DIM: usize = 2;

// ══════════════════════════════════════════════════════════════
// BORROMEAN TOPOLOGY CONSTANTS
// ══════════════════════════════════════════════════════════════

/// Number of rings in a Borromean link.
pub const BORROMEAN_RING_COUNT: usize = 3;

/// The modulus for the Borromean XOR invariant (Z/3Z).
pub const BORROMEAN_MODULUS: u8 = 3;

// ══════════════════════════════════════════════════════════════
// FRAMEWORK IDENTITY
// ══════════════════════════════════════════════════════════════

/// The Salvi Framework identifier.
pub const FRAMEWORK: &str = "Salvi Framework";

/// The division responsible for this codebase.
pub const DIVISION: &str = "Applied Physics Division";

/// The organization.
pub const ORG: &str = "Capomastro Holdings Ltd.";

// ══════════════════════════════════════════════════════════════
// CONVERSION UTILITIES (pure functions of the constants above)
// ══════════════════════════════════════════════════════════════

/// Convert ternary degrees (364° full circle) to conventional degrees (360°).
#[inline]
pub fn ternary_deg_to_std_deg(ternary_deg: f64) -> f64 {
    ternary_deg * (360.0 / FULL_CIRCLE_DEG)
}

/// Convert conventional degrees (360° full circle) to ternary degrees (364°).
#[inline]
pub fn std_deg_to_ternary_deg(std_deg: f64) -> f64 {
    std_deg * (FULL_CIRCLE_DEG / 360.0)
}

/// Convert ternary radians (28 per circle) to standard radians (2π per circle).
#[inline]
pub fn ternary_rad_to_std_rad(ternary_rad: f64) -> f64 {
    ternary_rad * (2.0 * STD_PI / TWO_PI_TERNARY)
}

/// Convert standard radians to ternary radians.
#[inline]
pub fn std_rad_to_ternary_rad(std_rad: f64) -> f64 {
    std_rad * (TWO_PI_TERNARY / (2.0 * STD_PI))
}

/// Convert ternary degrees to ternary radians.
#[inline]
pub fn ternary_deg_to_ternary_rad(deg: f64) -> f64 {
    deg / RADIAN_DEG
}

/// Convert ternary radians to ternary degrees.
#[inline]
pub fn ternary_rad_to_ternary_deg(rad: f64) -> f64 {
    rad * RADIAN_DEG
}

/// Convert a trit digit (0, 1, or 2) to its walk angle in ternary degrees.
#[inline]
pub fn trit_to_walk_angle_deg(trit: u8) -> f64 {
    debug_assert!(trit <= 2, "Trit must be 0, 1, or 2; got {}", trit);
    trit as f64 * RADIAN_DEG
}

/// Convert a trit digit to its walk angle in standard radians.
#[inline]
pub fn trit_to_std_rad(trit: u8) -> f64 {
    ternary_rad_to_std_rad(trit as f64)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn full_circle_bound() {
        assert_eq!(FULL_CIRCLE_DEG, RADIAN_DEG * TWO_PI_TERNARY);
        assert_eq!(364.0, 13.0 * 28.0);
    }

    #[test]
    fn pi_bound() {
        assert_eq!(PI_TERNARY, TWO_PI_TERNARY / 2.0);
    }

    #[test]
    fn cyclic_order_matches() {
        assert_eq!(CYCLIC_ORDER, RADIANS_PER_CIRCLE);
        assert_eq!(CYCLIC_ORDER, Z28_DIMENSIONS);
    }

    #[test]
    fn tau_identity() {
        let tau = TAU_TRIBONACCI;
        let tau_cubed = tau * tau * tau;
        let tau_sq_plus_tau_plus_1 = TAU_SQUARED + TAU_TRIBONACCI + 1.0;
        assert!((tau_cubed - tau_sq_plus_tau_plus_1).abs() < 1e-8,
            "τ³ should equal τ² + τ + 1");
    }

    #[test]
    fn conversion_round_trip_deg() {
        let std = ternary_deg_to_std_deg(FULL_CIRCLE_DEG);
        assert!((std - 360.0).abs() < 1e-10);
        let back = std_deg_to_ternary_deg(std);
        assert!((back - FULL_CIRCLE_DEG).abs() < 1e-10);
    }

    #[test]
    fn conversion_round_trip_rad() {
        let std = ternary_rad_to_std_rad(TWO_PI_TERNARY);
        assert!((std - 2.0 * STD_PI).abs() < 1e-10);
        let back = std_rad_to_ternary_rad(std);
        assert!((back - TWO_PI_TERNARY).abs() < 1e-10);
    }

    #[test]
    fn radian_conversion() {
        assert_eq!(ternary_rad_to_ternary_deg(1.0), RADIAN_DEG);
        assert_eq!(ternary_deg_to_ternary_rad(RADIAN_DEG), 1.0);
    }

    #[test]
    fn trit_walk_angles() {
        assert_eq!(trit_to_walk_angle_deg(0), WALK_TURN_0);
        assert_eq!(trit_to_walk_angle_deg(1), WALK_TURN_1);
        assert_eq!(trit_to_walk_angle_deg(2), WALK_TURN_2);
    }
}
